plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'maven-publish'
}

version = project.findProperty('mod_version') ?: '1.0.0'
base {
    archivesName = "weatherrythme-forge-${project.findProperty('minecraft_version') ?: '1.20.1'}"
}

def mcVersion = project.findProperty('minecraft_version') ?: '1.20.1'
def forgeVersion = project.findProperty('forge_version') ?: '47.3.0'

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${mcVersion}-${forgeVersion}"
}

minecraft {
    mappings channel: 'official', version: mcVersion
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
    withSourcesJar()
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'WeatherRythme',
            'Specification-Vendor'    : 'Mills520',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version
        ])
    }
}
